from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class TrainConfig:
    env_name: str = "5_vs_5"
    representation: str = "simple115v2"
    rewards: str = "scoring"
    num_controlled_players: int = 4
    num_envs: int = 1
    channel_dimensions: tuple[int, int] = (42, 42)
    render: bool = False
    use_engineered_features: bool = False
    collect_feature_metrics: bool = False
    action_set: str = "full"

    head_dim: int = 16
    trunk_dim: int = 64
    critic_dim: int = 64

    total_timesteps: int = 400_000
    rollout_steps: int = 256
    update_epochs: int = 2
    num_minibatches: int = 2
    learning_rate: float = 1e-4
    gamma: float = 0.995
    gae_lambda: float = 0.95
    clip_coef: float = 0.15
    ent_coef: float = 0.003
    vf_coef: float = 0.7
    max_grad_norm: float = 0.5

    seed: int = 42
    save_interval: int = 20
    log_interval: int = 1
    save_dir: str = "X_Jiang/checkpoints"
    logdir: str = "X_Jiang/logs"
    device: str = "auto"
    init_checkpoint: str | None = None
    prior_kl_coef: float = 0.0
    prior_kl_decay_updates: int = 0
    bc_coef: float = 0.0
    bc_decay_updates: int = 0
    bc_shoot_x_threshold: float = 0.45
    bc_shoot_y_threshold: float = 0.16
    force_shoot_in_zone: bool = False
    force_shoot_x_threshold: float = 0.3
    force_shoot_y_threshold: float = 0.24

    use_reward_shaping: bool = True
    possession_gain_reward: float = 0.15
    possession_loss_penalty: float = 0.15
    team_possession_reward: float = 0.001
    opponent_possession_penalty: float = 0.001
    successful_pass_reward: float = 0.03
    progressive_pass_reward_scale: float = 0.08
    carry_progress_reward_scale: float = 0.05
    attacking_third_reward: float = 0.002
    shot_with_ball_reward: float = 0.005
    checkpoint_reward_scale: float = 0.03
    attacking_risk_x_threshold: float = 0.4
    shot_reward_x_threshold: float = 0.35
    danger_zone_x_threshold: float = 0.2
    danger_zone_entry_reward: float = 0.015
    terminal_zone_x_threshold: float = 0.55
    terminal_zone_reward: float = 0.02
    finish_quality_threshold: float = 0.35
    finish_quality_progress_reward_scale: float = 0.04
    duel_reward_scale: float = 0.06
    low_quality_shot_penalty_scale: float = 0.04
    backtracking_penalty_scale: float = 0.04
    danger_zone_stall_penalty: float = 0.01
    bad_shot_penalty: float = 0.02
    attacking_loss_penalty_scale: float = 0.6
    out_of_play_loss_penalty: float = 0.05


COMMON_FOOTBALL: dict[str, Any] = {
    "representation": "simple115v2",
    "rewards": "scoring",
    "channel_dimensions": (42, 42),
    "num_envs": 1,
    "use_engineered_features": False,
    "collect_feature_metrics": False,
    "action_set": "full",
    "head_dim": 16,
    "trunk_dim": 64,
    "critic_dim": 64,
    "learning_rate": 1e-4,
    "gamma": 0.995,
    "gae_lambda": 0.95,
    "clip_coef": 0.15,
    "ent_coef": 0.003,
    "vf_coef": 0.7,
    "max_grad_norm": 0.5,
    "update_epochs": 2,
    "num_minibatches": 2,
    "use_reward_shaping": True,
    "possession_gain_reward": 0.15,
    "possession_loss_penalty": 0.15,
    "team_possession_reward": 0.001,
    "opponent_possession_penalty": 0.001,
    "successful_pass_reward": 0.03,
    "progressive_pass_reward_scale": 0.08,
    "carry_progress_reward_scale": 0.05,
    "attacking_third_reward": 0.002,
    "shot_with_ball_reward": 0.005,
    "checkpoint_reward_scale": 0.03,
    "attacking_risk_x_threshold": 0.4,
    "shot_reward_x_threshold": 0.35,
    "danger_zone_x_threshold": 0.2,
    "danger_zone_entry_reward": 0.015,
    "terminal_zone_x_threshold": 0.55,
    "terminal_zone_reward": 0.02,
    "finish_quality_threshold": 0.35,
    "finish_quality_progress_reward_scale": 0.04,
    "duel_reward_scale": 0.06,
    "low_quality_shot_penalty_scale": 0.04,
    "backtracking_penalty_scale": 0.04,
    "danger_zone_stall_penalty": 0.01,
    "bad_shot_penalty": 0.02,
    "attacking_loss_penalty_scale": 0.6,
    "out_of_play_loss_penalty": 0.05,
    "device": "auto",
    "prior_kl_coef": 0.0,
    "prior_kl_decay_updates": 0,
    "bc_coef": 0.0,
    "bc_decay_updates": 0,
    "bc_shoot_x_threshold": 0.45,
    "bc_shoot_y_threshold": 0.16,
    "force_shoot_in_zone": False,
    "force_shoot_x_threshold": 0.3,
    "force_shoot_y_threshold": 0.24,
}


PRESETS: dict[str, dict[str, Any]] = {
    "academy_empty_goal_close_curriculum": {
        **COMMON_FOOTBALL,
        "env_name": "academy_empty_goal_close",
        "num_controlled_players": 1,
        "num_envs": 4,
        "action_set": "solo_minimal",
        "total_timesteps": 12_800,
        "rollout_steps": 64,
        "save_interval": 20,
        "learning_rate": 1e-4,
        "clip_coef": 0.15,
        "ent_coef": 0.003,
        "prior_kl_coef": 0.0,
        "prior_kl_decay_updates": 0,
        "bc_coef": 0.0,
        "bc_decay_updates": 0,
        "save_dir": "X_Jiang/checkpoints/academy_empty_goal_close_curriculum",
        "logdir": "X_Jiang/logs/academy_empty_goal_close_curriculum",
        "possession_gain_reward": 0.0,
        "possession_loss_penalty": 0.0,
        "team_possession_reward": 0.0,
        "opponent_possession_penalty": 0.0,
        "successful_pass_reward": 0.0,
        "progressive_pass_reward_scale": 0.0,
        "carry_progress_reward_scale": 0.0,
        "attacking_third_reward": 0.0,
        "shot_with_ball_reward": 0.0,
        "checkpoint_reward_scale": 0.08,
        "danger_zone_x_threshold": 0.0,
        "danger_zone_entry_reward": 0.0,
        "terminal_zone_x_threshold": 0.75,
        "terminal_zone_reward": 0.0,
        "finish_quality_progress_reward_scale": 0.0,
        "duel_reward_scale": 0.0,
        "low_quality_shot_penalty_scale": 0.02,
        "backtracking_penalty_scale": 0.01,
        "danger_zone_stall_penalty": 0.0,
        "bad_shot_penalty": 0.0,
    },
    "academy_empty_goal_curriculum": {
        **COMMON_FOOTBALL,
        "env_name": "academy_empty_goal",
        "num_controlled_players": 1,
        "num_envs": 4,
        "action_set": "solo_minimal",
        "total_timesteps": 19_200,
        "rollout_steps": 64,
        "save_interval": 20,
        "learning_rate": 1e-4,
        "clip_coef": 0.15,
        "ent_coef": 0.003,
        "prior_kl_coef": 0.0,
        "prior_kl_decay_updates": 0,
        "bc_coef": 0.0,
        "bc_decay_updates": 0,
        "save_dir": "X_Jiang/checkpoints/academy_empty_goal_curriculum",
        "logdir": "X_Jiang/logs/academy_empty_goal_curriculum",
        "possession_gain_reward": 0.0,
        "possession_loss_penalty": 0.0,
        "team_possession_reward": 0.0,
        "opponent_possession_penalty": 0.0,
        "successful_pass_reward": 0.0,
        "progressive_pass_reward_scale": 0.0,
        "carry_progress_reward_scale": 0.0,
        "attacking_third_reward": 0.0,
        "shot_with_ball_reward": 0.0,
        "checkpoint_reward_scale": 0.08,
        "danger_zone_x_threshold": 0.0,
        "danger_zone_entry_reward": 0.0,
        "terminal_zone_x_threshold": 0.75,
        "terminal_zone_reward": 0.0,
        "finish_quality_progress_reward_scale": 0.0,
        "duel_reward_scale": 0.0,
        "low_quality_shot_penalty_scale": 0.03,
        "backtracking_penalty_scale": 0.01,
        "danger_zone_stall_penalty": 0.0,
        "bad_shot_penalty": 0.0,
    },
    "academy_run_to_score_official_clean": {
        **COMMON_FOOTBALL,
        "env_name": "academy_run_to_score_with_keeper",
        "num_controlled_players": 1,
        "num_envs": 4,
        "action_set": "solo_minimal",
        "total_timesteps": 25_600,
        "rollout_steps": 64,
        "save_interval": 25,
        "learning_rate": 1e-4,
        "clip_coef": 0.15,
        "ent_coef": 0.003,
        "prior_kl_coef": 0.0,
        "prior_kl_decay_updates": 0,
        "bc_coef": 0.0,
        "bc_decay_updates": 0,
        "force_shoot_in_zone": False,
        "save_dir": "X_Jiang/checkpoints/academy_run_to_score_official_clean",
        "logdir": "X_Jiang/logs/academy_run_to_score_official_clean",
        "possession_gain_reward": 0.0,
        "possession_loss_penalty": 0.0,
        "team_possession_reward": 0.0,
        "opponent_possession_penalty": 0.0,
        "carry_progress_reward_scale": 0.0,
        "successful_pass_reward": 0.0,
        "progressive_pass_reward_scale": 0.0,
        "attacking_third_reward": 0.0,
        "checkpoint_reward_scale": 0.06,
        "attacking_risk_x_threshold": 0.45,
        "shot_reward_x_threshold": 0.60,
        "danger_zone_x_threshold": 0.0,
        "danger_zone_entry_reward": 0.0,
        "terminal_zone_x_threshold": 0.75,
        "terminal_zone_reward": 0.0,
        "shot_with_ball_reward": 0.0,
        "finish_quality_threshold": 0.60,
        "finish_quality_progress_reward_scale": 0.0,
        "duel_reward_scale": 0.0,
        "low_quality_shot_penalty_scale": 0.03,
        "backtracking_penalty_scale": 0.01,
        "danger_zone_stall_penalty": 0.0,
        "bad_shot_penalty": 0.0,
    },
    "academy_run_to_score_clean": {
        **COMMON_FOOTBALL,
        "env_name": "academy_run_to_score",
        "num_controlled_players": 1,
        "num_envs": 4,
        "action_set": "solo_minimal",
        "total_timesteps": 25_600,
        "rollout_steps": 64,
        "save_interval": 25,
        "learning_rate": 1e-4,
        "clip_coef": 0.15,
        "ent_coef": 0.003,
        "prior_kl_coef": 0.0,
        "prior_kl_decay_updates": 0,
        "bc_coef": 0.0,
        "bc_decay_updates": 0,
        "force_shoot_in_zone": False,
        "save_dir": "X_Jiang/checkpoints/academy_run_to_score_clean",
        "logdir": "X_Jiang/logs/academy_run_to_score_clean",
        "possession_gain_reward": 0.0,
        "possession_loss_penalty": 0.0,
        "team_possession_reward": 0.0,
        "opponent_possession_penalty": 0.0,
        "carry_progress_reward_scale": 0.0,
        "successful_pass_reward": 0.0,
        "progressive_pass_reward_scale": 0.0,
        "attacking_third_reward": 0.0,
        "checkpoint_reward_scale": 0.06,
        "attacking_risk_x_threshold": 0.45,
        "shot_reward_x_threshold": 0.60,
        "danger_zone_x_threshold": 0.0,
        "danger_zone_entry_reward": 0.0,
        "terminal_zone_x_threshold": 0.75,
        "terminal_zone_reward": 0.0,
        "shot_with_ball_reward": 0.0,
        "finish_quality_threshold": 0.60,
        "finish_quality_progress_reward_scale": 0.0,
        "duel_reward_scale": 0.0,
        "low_quality_shot_penalty_scale": 0.03,
        "backtracking_penalty_scale": 0.01,
        "danger_zone_stall_penalty": 0.0,
        "bad_shot_penalty": 0.0,
    },
    "academy_run_to_score_relaxed_curriculum": {
        **COMMON_FOOTBALL,
        "env_name": "academy_run_to_score_relaxed",
        "num_controlled_players": 1,
        "num_envs": 4,
        "action_set": "solo_academy",
        "total_timesteps": 25_600,
        "rollout_steps": 64,
        "save_interval": 25,
        "learning_rate": 1e-4,
        "clip_coef": 0.15,
        "ent_coef": 0.002,
        "prior_kl_coef": 0.0,
        "prior_kl_decay_updates": 0,
        "bc_coef": 0.0,
        "bc_decay_updates": 0,
        "force_shoot_in_zone": False,
        "save_dir": "X_Jiang/checkpoints/academy_run_to_score_relaxed_curriculum",
        "logdir": "X_Jiang/logs/academy_run_to_score_relaxed_curriculum",
        "possession_gain_reward": 0.0,
        "possession_loss_penalty": 0.0,
        "team_possession_reward": 0.0,
        "opponent_possession_penalty": 0.0,
        "successful_pass_reward": 0.0,
        "progressive_pass_reward_scale": 0.0,
        "carry_progress_reward_scale": 0.0,
        "attacking_third_reward": 0.0,
        "checkpoint_reward_scale": 0.035,
        "attacking_risk_x_threshold": 0.35,
        "shot_reward_x_threshold": 0.55,
        "danger_zone_x_threshold": 0.22,
        "danger_zone_entry_reward": 0.015,
        "terminal_zone_x_threshold": 0.48,
        "terminal_zone_reward": 0.03,
        "shot_with_ball_reward": 0.0,
        "finish_quality_threshold": 0.58,
        "finish_quality_progress_reward_scale": 0.03,
        "duel_reward_scale": 0.05,
        "low_quality_shot_penalty_scale": 0.035,
        "backtracking_penalty_scale": 0.01,
        "danger_zone_stall_penalty": 0.01,
        "bad_shot_penalty": 0.0,
    },
    "academy_1v1_defended_bridge": {
        **COMMON_FOOTBALL,
        "env_name": "academy_1_vs_1_relaxed",
        "num_controlled_players": 1,
        "num_envs": 2,
        "action_set": "solo_academy",
        "total_timesteps": 25_600,
        "rollout_steps": 32,
        "save_interval": 25,
        "learning_rate": 1e-4,
        "clip_coef": 0.15,
        "ent_coef": 0.002,
        "prior_kl_coef": 0.0,
        "prior_kl_decay_updates": 0,
        "bc_coef": 0.0,
        "bc_decay_updates": 0,
        "force_shoot_in_zone": False,
        "save_dir": "X_Jiang/checkpoints/academy_1v1_defended_bridge",
        "logdir": "X_Jiang/logs/academy_1v1_defended_bridge",
        "possession_gain_reward": 0.0,
        "possession_loss_penalty": 0.0,
        "team_possession_reward": 0.0,
        "opponent_possession_penalty": 0.0,
        "successful_pass_reward": 0.0,
        "progressive_pass_reward_scale": 0.0,
        "carry_progress_reward_scale": 0.0,
        "attacking_third_reward": 0.0,
        "checkpoint_reward_scale": 0.025,
        "attacking_risk_x_threshold": 0.28,
        "shot_reward_x_threshold": 0.42,
        "danger_zone_x_threshold": 0.20,
        "danger_zone_entry_reward": 0.02,
        "terminal_zone_x_threshold": 0.42,
        "terminal_zone_reward": 0.04,
        "shot_with_ball_reward": 0.0,
        "finish_quality_threshold": 0.48,
        "finish_quality_progress_reward_scale": 0.05,
        "duel_reward_scale": 0.08,
        "low_quality_shot_penalty_scale": 0.04,
        "backtracking_penalty_scale": 0.01,
        "danger_zone_stall_penalty": 0.01,
        "bad_shot_penalty": 0.0,
    },
    "academy_1v1_close_bridge_fast": {
        **COMMON_FOOTBALL,
        "env_name": "academy_1_vs_1_close_bridge",
        "num_controlled_players": 1,
        "num_envs": 1,
        "action_set": "solo_minimal",
        "total_timesteps": 1_600,
        "rollout_steps": 16,
        "save_interval": 10,
        "learning_rate": 1e-4,
        "clip_coef": 0.15,
        "ent_coef": 0.002,
        "prior_kl_coef": 0.0,
        "prior_kl_decay_updates": 0,
        "bc_coef": 0.0,
        "bc_decay_updates": 0,
        "force_shoot_in_zone": False,
        "save_dir": "X_Jiang/checkpoints/academy_1v1_close_bridge_fast",
        "logdir": "X_Jiang/logs/academy_1v1_close_bridge_fast",
        "possession_gain_reward": 0.0,
        "possession_loss_penalty": 0.0,
        "team_possession_reward": 0.0,
        "opponent_possession_penalty": 0.0,
        "successful_pass_reward": 0.0,
        "progressive_pass_reward_scale": 0.0,
        "carry_progress_reward_scale": 0.0,
        "attacking_third_reward": 0.0,
        "checkpoint_reward_scale": 0.02,
        "attacking_risk_x_threshold": 0.35,
        "shot_reward_x_threshold": 0.55,
        "danger_zone_x_threshold": 0.45,
        "danger_zone_entry_reward": 0.02,
        "terminal_zone_x_threshold": 0.58,
        "terminal_zone_reward": 0.05,
        "shot_with_ball_reward": 0.0,
        "finish_quality_threshold": 0.52,
        "finish_quality_progress_reward_scale": 0.04,
        "duel_reward_scale": 0.06,
        "low_quality_shot_penalty_scale": 0.03,
        "backtracking_penalty_scale": 0.01,
        "danger_zone_stall_penalty": 0.01,
        "bad_shot_penalty": 0.0,
    },
    "academy_stage3_mainline": {
        **COMMON_FOOTBALL,
        "env_name": "academy_1_vs_1_close_bridge",
        "num_controlled_players": 1,
        "num_envs": 1,
        "action_set": "solo_minimal",
        "total_timesteps": 1_600,
        "rollout_steps": 16,
        "save_interval": 10,
        "learning_rate": 1e-4,
        "clip_coef": 0.15,
        "ent_coef": 0.002,
        "prior_kl_coef": 0.0,
        "prior_kl_decay_updates": 0,
        "bc_coef": 0.0,
        "bc_decay_updates": 0,
        "force_shoot_in_zone": False,
        "init_checkpoint": "X_Jiang/checkpoints/academy_empty_goal_curriculum/best.pt",
        "save_dir": "X_Jiang/checkpoints/academy_stage3_mainline",
        "logdir": "X_Jiang/logs/academy_stage3_mainline",
        "possession_gain_reward": 0.0,
        "possession_loss_penalty": 0.0,
        "team_possession_reward": 0.0,
        "opponent_possession_penalty": 0.0,
        "successful_pass_reward": 0.0,
        "progressive_pass_reward_scale": 0.0,
        "carry_progress_reward_scale": 0.0,
        "attacking_third_reward": 0.0,
        "checkpoint_reward_scale": 0.02,
        "attacking_risk_x_threshold": 0.35,
        "shot_reward_x_threshold": 0.55,
        "danger_zone_x_threshold": 0.45,
        "danger_zone_entry_reward": 0.02,
        "terminal_zone_x_threshold": 0.58,
        "terminal_zone_reward": 0.05,
        "shot_with_ball_reward": 0.0,
        "finish_quality_threshold": 0.52,
        "finish_quality_progress_reward_scale": 0.04,
        "duel_reward_scale": 0.06,
        "low_quality_shot_penalty_scale": 0.03,
        "backtracking_penalty_scale": 0.01,
        "danger_zone_stall_penalty": 0.01,
        "bad_shot_penalty": 0.0,
    },
    "academy_run_to_score_official_foundation": {
        **COMMON_FOOTBALL,
        "env_name": "academy_run_to_score_with_keeper",
        "num_controlled_players": 1,
        "num_envs": 4,
        "action_set": "solo_academy",
        "total_timesteps": 32_768,
        "rollout_steps": 64,
        "save_interval": 20,
        "learning_rate": 2e-5,
        "clip_coef": 0.06,
        "ent_coef": 0.0003,
        "prior_kl_coef": 0.10,
        "prior_kl_decay_updates": 128,
        "bc_coef": 0.05,
        "bc_decay_updates": 72,
        "bc_shoot_x_threshold": 0.52,
        "bc_shoot_y_threshold": 0.16,
        "force_shoot_in_zone": False,
        "force_shoot_x_threshold": 0.3,
        "force_shoot_y_threshold": 0.24,
        "save_dir": "X_Jiang/checkpoints/academy_run_to_score_official_foundation",
        "logdir": "X_Jiang/logs/academy_run_to_score_official_foundation",
        "possession_gain_reward": 0.0,
        "possession_loss_penalty": 0.0,
        "team_possession_reward": 0.0,
        "opponent_possession_penalty": 0.0,
        "carry_progress_reward_scale": 0.0,
        "successful_pass_reward": 0.0,
        "progressive_pass_reward_scale": 0.0,
        "attacking_third_reward": 0.0,
        "checkpoint_reward_scale": 0.006,
        "attacking_risk_x_threshold": 0.38,
        "shot_reward_x_threshold": 0.48,
        "danger_zone_x_threshold": 0.38,
        "danger_zone_entry_reward": 0.04,
        "terminal_zone_x_threshold": 0.58,
        "terminal_zone_reward": 0.10,
        "shot_with_ball_reward": 0.05,
        "finish_quality_threshold": 0.48,
        "finish_quality_progress_reward_scale": 0.08,
        "duel_reward_scale": 0.12,
        "low_quality_shot_penalty_scale": 0.08,
        "backtracking_penalty_scale": 0.06,
        "danger_zone_stall_penalty": 0.02,
        "bad_shot_penalty": 0.04,
    },
    "academy_run_to_score_attack_foundation": {
        **COMMON_FOOTBALL,
        "env_name": "academy_1_vs_1_with_keeper",
        "num_controlled_players": 1,
        "num_envs": 4,
        "action_set": "solo_academy",
        "total_timesteps": 32_768,
        "rollout_steps": 64,
        "save_interval": 20,
        "learning_rate": 2e-5,
        "clip_coef": 0.06,
        "ent_coef": 0.0003,
        "prior_kl_coef": 0.10,
        "prior_kl_decay_updates": 128,
        "bc_coef": 0.05,
        "bc_decay_updates": 72,
        "bc_shoot_x_threshold": 0.42,
        "bc_shoot_y_threshold": 0.18,
        "force_shoot_in_zone": False,
        "force_shoot_x_threshold": 0.3,
        "force_shoot_y_threshold": 0.24,
        "save_dir": "X_Jiang/checkpoints/academy_run_to_score_attack_foundation",
        "logdir": "X_Jiang/logs/academy_run_to_score_attack_foundation",
        "possession_gain_reward": 0.0,
        "possession_loss_penalty": 0.0,
        "team_possession_reward": 0.0,
        "opponent_possession_penalty": 0.0,
        "carry_progress_reward_scale": 0.0,
        "successful_pass_reward": 0.0,
        "progressive_pass_reward_scale": 0.0,
        "attacking_third_reward": 0.0,
        "checkpoint_reward_scale": 0.008,
        "attacking_risk_x_threshold": 0.32,
        "shot_reward_x_threshold": 0.40,
        "danger_zone_x_threshold": 0.30,
        "danger_zone_entry_reward": 0.04,
        "terminal_zone_x_threshold": 0.48,
        "terminal_zone_reward": 0.10,
        "shot_with_ball_reward": 0.05,
        "finish_quality_threshold": 0.46,
        "finish_quality_progress_reward_scale": 0.08,
        "duel_reward_scale": 0.12,
        "low_quality_shot_penalty_scale": 0.08,
        "backtracking_penalty_scale": 0.06,
        "danger_zone_stall_penalty": 0.02,
        "bad_shot_penalty": 0.04,
    },
    "academy_pass_and_shoot_attack_support": {
        **COMMON_FOOTBALL,
        "env_name": "academy_pass_and_shoot_with_keeper",
        "num_controlled_players": 2,
        "num_envs": 4,
        "action_set": "academy",
        "total_timesteps": 24_576,
        "rollout_steps": 64,
        "save_interval": 50,
        "learning_rate": 1e-4,
        "clip_coef": 0.15,
        "ent_coef": 0.003,
        "prior_kl_coef": 0.0,
        "prior_kl_decay_updates": 0,
        "bc_coef": 0.0,
        "bc_decay_updates": 0,
        "save_dir": "X_Jiang/checkpoints/academy_pass_and_shoot_attack_support",
        "logdir": "X_Jiang/logs/academy_pass_and_shoot_attack_support",
        "possession_gain_reward": 0.0,
        "possession_loss_penalty": 0.0,
        "team_possession_reward": 0.0,
        "opponent_possession_penalty": 0.0,
        "successful_pass_reward": 0.04,
        "progressive_pass_reward_scale": 0.10,
        "carry_progress_reward_scale": 0.0,
        "attacking_third_reward": 0.0,
        "checkpoint_reward_scale": 0.01,
        "danger_zone_entry_reward": 0.0,
        "terminal_zone_reward": 0.0,
        "shot_with_ball_reward": 0.0,
        "finish_quality_progress_reward_scale": 0.0,
        "duel_reward_scale": 0.0,
        "low_quality_shot_penalty_scale": 0.02,
        "backtracking_penalty_scale": 0.01,
        "danger_zone_stall_penalty": 0.0,
        "bad_shot_penalty": 0.0,
    },
    "academy_pass_and_shoot_curriculum": {
        **COMMON_FOOTBALL,
        "env_name": "academy_pass_and_shoot_with_keeper",
        "num_controlled_players": 2,
        "num_envs": 4,
        "action_set": "academy",
        "total_timesteps": 24_576,
        "rollout_steps": 64,
        "save_interval": 50,
        "learning_rate": 1e-4,
        "clip_coef": 0.15,
        "ent_coef": 0.003,
        "prior_kl_coef": 0.0,
        "prior_kl_decay_updates": 0,
        "bc_coef": 0.0,
        "bc_decay_updates": 0,
        "save_dir": "X_Jiang/checkpoints/academy_pass_and_shoot_curriculum",
        "logdir": "X_Jiang/logs/academy_pass_and_shoot_curriculum",
        "possession_gain_reward": 0.0,
        "possession_loss_penalty": 0.0,
        "team_possession_reward": 0.0,
        "opponent_possession_penalty": 0.0,
        "successful_pass_reward": 0.04,
        "progressive_pass_reward_scale": 0.10,
        "carry_progress_reward_scale": 0.0,
        "attacking_third_reward": 0.0,
        "checkpoint_reward_scale": 0.01,
        "danger_zone_entry_reward": 0.0,
        "terminal_zone_reward": 0.0,
        "shot_with_ball_reward": 0.0,
        "finish_quality_progress_reward_scale": 0.0,
        "duel_reward_scale": 0.0,
        "low_quality_shot_penalty_scale": 0.02,
        "backtracking_penalty_scale": 0.01,
        "danger_zone_stall_penalty": 0.0,
        "bad_shot_penalty": 0.0,
    },
    "academy_3v1_attack_support": {
        **COMMON_FOOTBALL,
        "env_name": "academy_3_vs_1_with_keeper",
        "num_controlled_players": 3,
        "num_envs": 4,
        "action_set": "academy",
        "total_timesteps": 36_864,
        "rollout_steps": 64,
        "save_interval": 50,
        "save_dir": "X_Jiang/checkpoints/academy_3v1_attack_support",
        "logdir": "X_Jiang/logs/academy_3v1_attack_support",
        "successful_pass_reward": 0.04,
        "progressive_pass_reward_scale": 0.10,
        "carry_progress_reward_scale": 0.04,
        "shot_with_ball_reward": 0.01,
    },
    "five_v_five_football_base": {
        **COMMON_FOOTBALL,
        "env_name": "5_vs_5",
        "num_controlled_players": 4,
        "total_timesteps": 102_400,
        "rollout_steps": 512,
        "save_interval": 20,
        "save_dir": "X_Jiang/checkpoints/five_v_five_football_base",
        "logdir": "X_Jiang/logs/five_v_five_football_base",
    },
}


def build_config(preset_name: str, overrides: dict[str, Any] | None = None) -> TrainConfig:
    if preset_name not in PRESETS:
        raise ValueError(f"Unknown preset: {preset_name}. Available presets: {list(PRESETS)}")
    merged: dict[str, Any] = dict(PRESETS[preset_name])
    if overrides:
        merged.update(overrides)
    return TrainConfig(**merged)
